### ISSUE TITLE
Deployment using Heroku

### ISSUE THREAD

**Issue by jamesjose03** [jamesjose03/personal-website#2]
Deploy the website using Heroku CLI.

**Comment by aashish-ak** [comment]
We'll be needing heroku account credentials for that @jamesjose03

**Comment by jamesjose03** [comment]
@aashish-ak  Thank you for your response. For now, I will be deploying it using ghpages.
Closing this issue.

**Comment by jamesjose03** [comment]
@aashish-ak  Could you pls check the responsiveness issue #1?
