### ISSUE TITLE
BackEnd of Contact Form Required

### ISSUE THREAD

**Issue by jamesjose03** [jamesjose03/personal-website#3]
Link the contact form to Firebase.

**Comment by jamesjose03** [comment]
@LS05 Sure. Thank you for your interest. Pls do follow the contribution guidelines.

**Comment by LS05** [comment]
@jamesjose03 the package.json file is missing in the repository :)

**Comment by LS05** [comment]
Oh sorry, it's in the client folder. My bad :/

**Comment by LS05** [comment]
I think is better to specify that in the README, isn't it?

**Comment by jamesjose03** [comment]
@LS05 Thanks for suggesting. Will do it.

**Comment by jamesjose03** [comment]
@LS05 Store it to the real-time database.

**Comment by LS05** [comment]
@jamesjose03 ok cool!

**Comment by jamesjose03** [comment]
@LS05 Pls refer docs https://firebase.google.com/docs/database/ and tutorials.

**Comment by LS05** [comment]
@jamesjose03 got it. What about the api key and database url? Do you have those in place?

**Comment by jamesjose03** [comment]
Issue fixed by @LS05
